apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: devops
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/studentdb?createDatabaseIfNotExist=true"
  SPRING_DATASOURCE_USERNAME: "root"
  SERVER_PORT: "8089"
  SERVER_SERVLET_CONTEXT_PATH: "/student"

---
apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: devops
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: ""
